### ISSUE TITLE
Integration With Java

### ISSUE THREAD

**Issue by VIKZ57** [nikulkarni/webdriver-accessibility#2]
Hi Nilesh. Your tool on accessibility testing is awesome. Its reports are extensive and has clarity.

While integrating it with Java, is there any provision or workaround to get screeenshots (with highlighted issues)?If yes, could you please share it with me?

Thanks.

**Comment by nikulkarni** [comment]
Hi @VIKZ57, thanks for the kind words. 

The tool already does highlight errors on screenshot. This capability is already available. Please check this [code](https://github.com/nikulkarni/webdriver-accessibility/blob/master/src/main/java/com/accessibility/AccessibilityScanner.java#L52-L59) and [this](https://github.com/nikulkarni/webdriver-accessibility/blob/master/src/main/java/com/accessibility/AccessibilityScanner.java#L107-L114). So basically in the result map will have screenshot information in bytes. This is what you would do,

```
Map<String, Object> audit_report = scanner.runAccessibilityAudit();
if (audit_report != null && audit_report.containsKey("screenshot")) {
    final byte[] screenshot = (byte[]) audit_report.get("screenshot");
    scenario.embed(screenshot, "image/png");
}
```

Let me know if you have any issues.

**Comment by VIKZ57** [comment]
Hi Nilesh,

Thanks for replying to my mail! I am really sorry, I missed the code you
mentioned above. It worked for me.
Don't know, if I am bothering you too much, but I have one more query for
you! The js that you have used for detecting accessibility issues, it seems
to be quite old. Did you get chance to update it according to the latest
accessibility rules?

Regards,
Vikram.

**Comment by nikulkarni** [comment]
Sure will update the rules

**Comment by nikulkarni** [comment]
Hi @VIKZ57 , the rules I'm using should be the latest, since we are using the raw js from [here](https://github.com/GoogleChrome/accessibility-developer-tools#getting-the-code)

**Comment by nikulkarni** [comment]
Please reopen this if you think this doesn't answer the question, closing it now
